version: '3'

services:
    db:
        image: 'postgres:latest'
        env_file:
            - .env
        volumes:
            - ./volumes/db/:/var/lib/postgresql/data/
        restart: unless-stopped
    backend:
        image: ghcr.io/pl33/hta-backend:latest
        ports:
            - "${PORT}:8080"
        env_file:
            - .env
        environment:
            - DB=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
        restart: unless-stopped
