// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Health Tracker App
//
//	Track Health Parameters
//	Schemes:
//	  http
//	  https
//	Host: localhost:8080
//	BasePath: /
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
