// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http",
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Track Health Parameters",
    "title": "Health Tracker App",
    "version": "1.0.0"
  },
  "host": "localhost:8080",
  "paths": {
    "/category/": {
      "get": {
        "tags": [
          "category"
        ],
        "parameters": [
          {
            "type": "integer",
            "format": "int32",
            "default": 0,
            "name": "first",
            "in": "query"
          },
          {
            "type": "integer",
            "format": "int32",
            "name": "limit",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "List of categories",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/category"
              }
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "tags": [
          "category"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/category"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/category"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/category/{category_id}/multi_choice/": {
      "get": {
        "tags": [
          "category"
        ],
        "parameters": [
          {
            "type": "integer",
            "format": "int32",
            "default": 0,
            "name": "first",
            "in": "query"
          },
          {
            "type": "integer",
            "format": "int32",
            "name": "limit",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "List of multi choices",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/category_multi_choice"
              }
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "tags": [
          "category"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/category_multi_choice"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/category_multi_choice"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "integer",
          "format": "int64",
          "name": "category_id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/category/{category_id}/single_choice_group/": {
      "get": {
        "tags": [
          "category"
        ],
        "parameters": [
          {
            "type": "integer",
            "format": "int32",
            "default": 0,
            "name": "first",
            "in": "query"
          },
          {
            "type": "integer",
            "format": "int32",
            "name": "limit",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "List of single choice groups",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/category_single_choice_group"
              }
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "tags": [
          "category"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/category_single_choice_group"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/category_single_choice_group"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "integer",
          "format": "int64",
          "name": "category_id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/category/{id}": {
      "put": {
        "tags": [
          "category"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/category"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/category"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "category"
        ],
        "responses": {
          "204": {
            "description": "Deleted"
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "integer",
          "format": "int64",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/entries/": {
      "get": {
        "tags": [
          "entry"
        ],
        "parameters": [
          {
            "type": "integer",
            "format": "int32",
            "name": "first",
            "in": "query"
          },
          {
            "type": "integer",
            "format": "int32",
            "default": 20,
            "name": "limit",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "List of entries",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/entry"
              }
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/entries/{id}": {
      "put": {
        "tags": [
          "entry"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/entry"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/entry"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "entry"
        ],
        "responses": {
          "204": {
            "description": "Deleted"
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "integer",
          "format": "int64",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/login": {
      "get": {
        "security": [],
        "tags": [
          "login"
        ],
        "summary": "login through oauth2 server",
        "responses": {
          "200": {
            "description": "login",
            "schema": {
              "properties": {
                "access_token": {
                  "type": "string",
                  "format": "string"
                }
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/multi_choice/{id}": {
      "put": {
        "tags": [
          "category"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/category_multi_choice"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/category_multi_choice"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "category"
        ],
        "responses": {
          "204": {
            "description": "Deleted"
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "integer",
          "format": "int64",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/oidc_callback": {
      "get": {
        "security": [],
        "tags": [
          "login"
        ],
        "summary": "return access_token",
        "responses": {
          "200": {
            "description": "login",
            "schema": {
              "properties": {
                "access_token": {
                  "type": "string",
                  "format": "string"
                }
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/single_choice/{id}": {
      "put": {
        "tags": [
          "category"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/category_single_choice"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/category_single_choice"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "category"
        ],
        "responses": {
          "204": {
            "description": "Deleted"
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "integer",
          "format": "int64",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/single_choice_group/{group_id}/single_choice/": {
      "get": {
        "tags": [
          "category"
        ],
        "parameters": [
          {
            "type": "integer",
            "format": "int32",
            "default": 0,
            "name": "first",
            "in": "query"
          },
          {
            "type": "integer",
            "format": "int32",
            "name": "limit",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "List of single choices",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/category_single_choice"
              }
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "tags": [
          "category"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/category_single_choice"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/category_single_choice"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "integer",
          "format": "int64",
          "name": "group_id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/single_choice_group/{id}": {
      "put": {
        "tags": [
          "category"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/category_single_choice_group"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/category_single_choice_group"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "category"
        ],
        "responses": {
          "204": {
            "description": "Deleted"
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "integer",
          "format": "int64",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/user/": {
      "get": {
        "tags": [
          "login"
        ],
        "responses": {
          "200": {
            "description": "User info",
            "schema": {
              "$ref": "#/definitions/user"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "tags": [
          "entry"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/entry"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/entry"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "category": {
      "type": "object",
      "required": [
        "title"
      ],
      "properties": {
        "id": {
          "type": "number",
          "format": "int32",
          "readOnly": true
        },
        "title": {
          "type": "string"
        },
        "user_id": {
          "type": "number",
          "format": "int32",
          "readOnly": true
        }
      }
    },
    "category_multi_choice": {
      "type": "object",
      "required": [
        "title"
      ],
      "properties": {
        "category_id": {
          "type": "number",
          "format": "int32",
          "readOnly": true
        },
        "description": {
          "type": "string"
        },
        "id": {
          "type": "number",
          "format": "int32",
          "readOnly": true
        },
        "title": {
          "type": "string"
        }
      }
    },
    "category_single_choice": {
      "type": "object",
      "required": [
        "title"
      ],
      "properties": {
        "description": {
          "type": "string"
        },
        "group_id": {
          "type": "number",
          "format": "int32",
          "readOnly": true
        },
        "id": {
          "type": "number",
          "format": "int32",
          "readOnly": true
        },
        "title": {
          "type": "string"
        }
      }
    },
    "category_single_choice_group": {
      "type": "object",
      "required": [
        "title"
      ],
      "properties": {
        "category_id": {
          "type": "number",
          "format": "int32",
          "readOnly": true
        },
        "description": {
          "type": "string"
        },
        "id": {
          "type": "number",
          "format": "int32",
          "readOnly": true
        },
        "title": {
          "type": "string"
        }
      }
    },
    "entry": {
      "type": "object",
      "required": [
        "have_blood_pressure",
        "start_time",
        "multi_choices",
        "single_choices"
      ],
      "properties": {
        "diastole": {
          "type": "number",
          "format": "float"
        },
        "end_time": {
          "type": "string",
          "format": "date-time"
        },
        "have_blood_pressure": {
          "type": "boolean"
        },
        "id": {
          "type": "number",
          "format": "int32",
          "readOnly": true
        },
        "multi_choices": {
          "type": "array",
          "items": {
            "type": "number",
            "format": "int64"
          }
        },
        "pulse": {
          "type": "number",
          "format": "float"
        },
        "single_choices": {
          "type": "array",
          "items": {
            "type": "number",
            "format": "int64"
          }
        },
        "start_time": {
          "type": "string",
          "format": "date-time"
        },
        "systole": {
          "type": "number",
          "format": "float"
        },
        "title": {
          "type": "string"
        },
        "user_id": {
          "type": "number",
          "format": "int32",
          "readOnly": true
        }
      }
    },
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "number",
          "format": "int32"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "user": {
      "type": "object",
      "properties": {
        "first_name": {
          "type": "string",
          "readOnly": true
        },
        "id": {
          "type": "number",
          "format": "int32",
          "readOnly": true
        },
        "name": {
          "type": "string",
          "readOnly": true
        }
      }
    }
  },
  "securityDefinitions": {
    "BearerToken": {
      "type": "apiKey",
      "name": "x-token",
      "in": "header"
    },
    "OauthSecurity": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://auth.philipple.de/auth/realms/Testing/protocol/openid-connect/auth",
      "tokenUrl": "https://auth.philipple.de/auth/realms/Testing/protocol/openid-connect/token",
      "scopes": {
        "admin": "Admin scope",
        "openid": "OpenID Connect",
        "user": "User scope"
      }
    }
  },
  "security": [
    {
      "BearerToken": []
    },
    {
      "OauthSecurity": [
        "openid"
      ]
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http",
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Track Health Parameters",
    "title": "Health Tracker App",
    "version": "1.0.0"
  },
  "host": "localhost:8080",
  "paths": {
    "/category/": {
      "get": {
        "tags": [
          "category"
        ],
        "parameters": [
          {
            "type": "integer",
            "format": "int32",
            "default": 0,
            "name": "first",
            "in": "query"
          },
          {
            "type": "integer",
            "format": "int32",
            "name": "limit",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "List of categories",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/category"
              }
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "tags": [
          "category"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/category"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/category"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/category/{category_id}/multi_choice/": {
      "get": {
        "tags": [
          "category"
        ],
        "parameters": [
          {
            "type": "integer",
            "format": "int32",
            "default": 0,
            "name": "first",
            "in": "query"
          },
          {
            "type": "integer",
            "format": "int32",
            "name": "limit",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "List of multi choices",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/category_multi_choice"
              }
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "tags": [
          "category"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/category_multi_choice"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/category_multi_choice"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "integer",
          "format": "int64",
          "name": "category_id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/category/{category_id}/single_choice_group/": {
      "get": {
        "tags": [
          "category"
        ],
        "parameters": [
          {
            "type": "integer",
            "format": "int32",
            "default": 0,
            "name": "first",
            "in": "query"
          },
          {
            "type": "integer",
            "format": "int32",
            "name": "limit",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "List of single choice groups",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/category_single_choice_group"
              }
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "tags": [
          "category"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/category_single_choice_group"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/category_single_choice_group"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "integer",
          "format": "int64",
          "name": "category_id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/category/{id}": {
      "put": {
        "tags": [
          "category"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/category"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/category"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "category"
        ],
        "responses": {
          "204": {
            "description": "Deleted"
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "integer",
          "format": "int64",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/entries/": {
      "get": {
        "tags": [
          "entry"
        ],
        "parameters": [
          {
            "type": "integer",
            "format": "int32",
            "name": "first",
            "in": "query"
          },
          {
            "type": "integer",
            "format": "int32",
            "default": 20,
            "name": "limit",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "List of entries",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/entry"
              }
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/entries/{id}": {
      "put": {
        "tags": [
          "entry"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/entry"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/entry"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "entry"
        ],
        "responses": {
          "204": {
            "description": "Deleted"
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "integer",
          "format": "int64",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/login": {
      "get": {
        "security": [],
        "tags": [
          "login"
        ],
        "summary": "login through oauth2 server",
        "responses": {
          "200": {
            "description": "login",
            "schema": {
              "properties": {
                "access_token": {
                  "type": "string",
                  "format": "string"
                }
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/multi_choice/{id}": {
      "put": {
        "tags": [
          "category"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/category_multi_choice"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/category_multi_choice"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "category"
        ],
        "responses": {
          "204": {
            "description": "Deleted"
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "integer",
          "format": "int64",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/oidc_callback": {
      "get": {
        "security": [],
        "tags": [
          "login"
        ],
        "summary": "return access_token",
        "responses": {
          "200": {
            "description": "login",
            "schema": {
              "properties": {
                "access_token": {
                  "type": "string",
                  "format": "string"
                }
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/single_choice/{id}": {
      "put": {
        "tags": [
          "category"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/category_single_choice"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/category_single_choice"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "category"
        ],
        "responses": {
          "204": {
            "description": "Deleted"
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "integer",
          "format": "int64",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/single_choice_group/{group_id}/single_choice/": {
      "get": {
        "tags": [
          "category"
        ],
        "parameters": [
          {
            "type": "integer",
            "format": "int32",
            "default": 0,
            "name": "first",
            "in": "query"
          },
          {
            "type": "integer",
            "format": "int32",
            "name": "limit",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "List of single choices",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/category_single_choice"
              }
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "tags": [
          "category"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/category_single_choice"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/category_single_choice"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "integer",
          "format": "int64",
          "name": "group_id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/single_choice_group/{id}": {
      "put": {
        "tags": [
          "category"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/category_single_choice_group"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/category_single_choice_group"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "category"
        ],
        "responses": {
          "204": {
            "description": "Deleted"
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "integer",
          "format": "int64",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    },
    "/user/": {
      "get": {
        "tags": [
          "login"
        ],
        "responses": {
          "200": {
            "description": "User info",
            "schema": {
              "$ref": "#/definitions/user"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "tags": [
          "entry"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/entry"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/entry"
            }
          },
          "default": {
            "description": "Error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "category": {
      "type": "object",
      "required": [
        "title"
      ],
      "properties": {
        "id": {
          "type": "number",
          "format": "int32",
          "readOnly": true
        },
        "title": {
          "type": "string"
        },
        "user_id": {
          "type": "number",
          "format": "int32",
          "readOnly": true
        }
      }
    },
    "category_multi_choice": {
      "type": "object",
      "required": [
        "title"
      ],
      "properties": {
        "category_id": {
          "type": "number",
          "format": "int32",
          "readOnly": true
        },
        "description": {
          "type": "string"
        },
        "id": {
          "type": "number",
          "format": "int32",
          "readOnly": true
        },
        "title": {
          "type": "string"
        }
      }
    },
    "category_single_choice": {
      "type": "object",
      "required": [
        "title"
      ],
      "properties": {
        "description": {
          "type": "string"
        },
        "group_id": {
          "type": "number",
          "format": "int32",
          "readOnly": true
        },
        "id": {
          "type": "number",
          "format": "int32",
          "readOnly": true
        },
        "title": {
          "type": "string"
        }
      }
    },
    "category_single_choice_group": {
      "type": "object",
      "required": [
        "title"
      ],
      "properties": {
        "category_id": {
          "type": "number",
          "format": "int32",
          "readOnly": true
        },
        "description": {
          "type": "string"
        },
        "id": {
          "type": "number",
          "format": "int32",
          "readOnly": true
        },
        "title": {
          "type": "string"
        }
      }
    },
    "entry": {
      "type": "object",
      "required": [
        "have_blood_pressure",
        "start_time",
        "multi_choices",
        "single_choices"
      ],
      "properties": {
        "diastole": {
          "type": "number",
          "format": "float"
        },
        "end_time": {
          "type": "string",
          "format": "date-time"
        },
        "have_blood_pressure": {
          "type": "boolean"
        },
        "id": {
          "type": "number",
          "format": "int32",
          "readOnly": true
        },
        "multi_choices": {
          "type": "array",
          "items": {
            "type": "number",
            "format": "int64"
          }
        },
        "pulse": {
          "type": "number",
          "format": "float"
        },
        "single_choices": {
          "type": "array",
          "items": {
            "type": "number",
            "format": "int64"
          }
        },
        "start_time": {
          "type": "string",
          "format": "date-time"
        },
        "systole": {
          "type": "number",
          "format": "float"
        },
        "title": {
          "type": "string"
        },
        "user_id": {
          "type": "number",
          "format": "int32",
          "readOnly": true
        }
      }
    },
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "number",
          "format": "int32"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "user": {
      "type": "object",
      "properties": {
        "first_name": {
          "type": "string",
          "readOnly": true
        },
        "id": {
          "type": "number",
          "format": "int32",
          "readOnly": true
        },
        "name": {
          "type": "string",
          "readOnly": true
        }
      }
    }
  },
  "securityDefinitions": {
    "BearerToken": {
      "type": "apiKey",
      "name": "x-token",
      "in": "header"
    },
    "OauthSecurity": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://auth.philipple.de/auth/realms/Testing/protocol/openid-connect/auth",
      "tokenUrl": "https://auth.philipple.de/auth/realms/Testing/protocol/openid-connect/token",
      "scopes": {
        "admin": "Admin scope",
        "openid": "OpenID Connect",
        "user": "User scope"
      }
    }
  },
  "security": [
    {
      "BearerToken": []
    },
    {
      "OauthSecurity": [
        "openid"
      ]
    }
  ]
}`))
}
