// Code generated by go-swagger; DO NOT EDIT.

package login

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetOidcCallbackHandlerFunc turns a function with the right signature into a get oidc callback handler
type GetOidcCallbackHandlerFunc func(GetOidcCallbackParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetOidcCallbackHandlerFunc) Handle(params GetOidcCallbackParams) middleware.Responder {
	return fn(params)
}

// GetOidcCallbackHandler interface for that can handle valid get oidc callback params
type GetOidcCallbackHandler interface {
	Handle(GetOidcCallbackParams) middleware.Responder
}

// NewGetOidcCallback creates a new http.Handler for the get oidc callback operation
func NewGetOidcCallback(ctx *middleware.Context, handler GetOidcCallbackHandler) *GetOidcCallback {
	return &GetOidcCallback{Context: ctx, Handler: handler}
}

/*
	GetOidcCallback swagger:route GET /oidc_callback login getOidcCallback

return access_token
*/
type GetOidcCallback struct {
	Context *middleware.Context
	Handler GetOidcCallbackHandler
}

func (o *GetOidcCallback) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetOidcCallbackParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetOidcCallbackOKBody get oidc callback o k body
//
// swagger:model GetOidcCallbackOKBody
type GetOidcCallbackOKBody struct {

	// access token
	AccessToken string `json:"access_token,omitempty"`
}

// Validate validates this get oidc callback o k body
func (o *GetOidcCallbackOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get oidc callback o k body based on context it is used
func (o *GetOidcCallbackOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetOidcCallbackOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetOidcCallbackOKBody) UnmarshalBinary(b []byte) error {
	var res GetOidcCallbackOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
