// Code generated by go-swagger; DO NOT EDIT.

package login

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/pl33/hta-backend/models"
)

// GetOidcCallbackOKCode is the HTTP code returned for type GetOidcCallbackOK
const GetOidcCallbackOKCode int = 200

/*
GetOidcCallbackOK login

swagger:response getOidcCallbackOK
*/
type GetOidcCallbackOK struct {

	/*
	  In: Body
	*/
	Payload *GetOidcCallbackOKBody `json:"body,omitempty"`
}

// NewGetOidcCallbackOK creates GetOidcCallbackOK with default headers values
func NewGetOidcCallbackOK() *GetOidcCallbackOK {

	return &GetOidcCallbackOK{}
}

// WithPayload adds the payload to the get oidc callback o k response
func (o *GetOidcCallbackOK) WithPayload(payload *GetOidcCallbackOKBody) *GetOidcCallbackOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get oidc callback o k response
func (o *GetOidcCallbackOK) SetPayload(payload *GetOidcCallbackOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOidcCallbackOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
GetOidcCallbackDefault error

swagger:response getOidcCallbackDefault
*/
type GetOidcCallbackDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetOidcCallbackDefault creates GetOidcCallbackDefault with default headers values
func NewGetOidcCallbackDefault(code int) *GetOidcCallbackDefault {
	if code <= 0 {
		code = 500
	}

	return &GetOidcCallbackDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get oidc callback default response
func (o *GetOidcCallbackDefault) WithStatusCode(code int) *GetOidcCallbackDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get oidc callback default response
func (o *GetOidcCallbackDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get oidc callback default response
func (o *GetOidcCallbackDefault) WithPayload(payload *models.Error) *GetOidcCallbackDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get oidc callback default response
func (o *GetOidcCallbackDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOidcCallbackDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
