// Code generated by go-swagger; DO NOT EDIT.

package login

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetOidcInfoHandlerFunc turns a function with the right signature into a get oidc info handler
type GetOidcInfoHandlerFunc func(GetOidcInfoParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetOidcInfoHandlerFunc) Handle(params GetOidcInfoParams) middleware.Responder {
	return fn(params)
}

// GetOidcInfoHandler interface for that can handle valid get oidc info params
type GetOidcInfoHandler interface {
	Handle(GetOidcInfoParams) middleware.Responder
}

// NewGetOidcInfo creates a new http.Handler for the get oidc info operation
func NewGetOidcInfo(ctx *middleware.Context, handler GetOidcInfoHandler) *GetOidcInfo {
	return &GetOidcInfo{Context: ctx, Handler: handler}
}

/*
	GetOidcInfo swagger:route GET /oidc_info login getOidcInfo

Obtain information about OpenID Connect
*/
type GetOidcInfo struct {
	Context *middleware.Context
	Handler GetOidcInfoHandler
}

func (o *GetOidcInfo) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetOidcInfoParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
