// Code generated by go-swagger; DO NOT EDIT.

package entry

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"hta_backend_2/models"
)

// DeleteEntriesIDNoContentCode is the HTTP code returned for type DeleteEntriesIDNoContent
const DeleteEntriesIDNoContentCode int = 204

/*
DeleteEntriesIDNoContent Deleted

swagger:response deleteEntriesIdNoContent
*/
type DeleteEntriesIDNoContent struct {
}

// NewDeleteEntriesIDNoContent creates DeleteEntriesIDNoContent with default headers values
func NewDeleteEntriesIDNoContent() *DeleteEntriesIDNoContent {

	return &DeleteEntriesIDNoContent{}
}

// WriteResponse to the client
func (o *DeleteEntriesIDNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

/*
DeleteEntriesIDDefault Error

swagger:response deleteEntriesIdDefault
*/
type DeleteEntriesIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteEntriesIDDefault creates DeleteEntriesIDDefault with default headers values
func NewDeleteEntriesIDDefault(code int) *DeleteEntriesIDDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteEntriesIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete entries ID default response
func (o *DeleteEntriesIDDefault) WithStatusCode(code int) *DeleteEntriesIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete entries ID default response
func (o *DeleteEntriesIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete entries ID default response
func (o *DeleteEntriesIDDefault) WithPayload(payload *models.Error) *DeleteEntriesIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete entries ID default response
func (o *DeleteEntriesIDDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteEntriesIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
