// Code generated by go-swagger; DO NOT EDIT.

package entry

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/pl33/hta-backend/models"
)

// PostEntriesCreatedCode is the HTTP code returned for type PostEntriesCreated
const PostEntriesCreatedCode int = 201

/*
PostEntriesCreated Created

swagger:response postEntriesCreated
*/
type PostEntriesCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Entry `json:"body,omitempty"`
}

// NewPostEntriesCreated creates PostEntriesCreated with default headers values
func NewPostEntriesCreated() *PostEntriesCreated {

	return &PostEntriesCreated{}
}

// WithPayload adds the payload to the post entries created response
func (o *PostEntriesCreated) WithPayload(payload *models.Entry) *PostEntriesCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post entries created response
func (o *PostEntriesCreated) SetPayload(payload *models.Entry) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostEntriesCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
PostEntriesDefault Error

swagger:response postEntriesDefault
*/
type PostEntriesDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostEntriesDefault creates PostEntriesDefault with default headers values
func NewPostEntriesDefault(code int) *PostEntriesDefault {
	if code <= 0 {
		code = 500
	}

	return &PostEntriesDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the post entries default response
func (o *PostEntriesDefault) WithStatusCode(code int) *PostEntriesDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the post entries default response
func (o *PostEntriesDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the post entries default response
func (o *PostEntriesDefault) WithPayload(payload *models.Error) *PostEntriesDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post entries default response
func (o *PostEntriesDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostEntriesDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
