// Code generated by go-swagger; DO NOT EDIT.

package entry

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/pl33/hta-backend/models"
)

// PutEntriesIDOKCode is the HTTP code returned for type PutEntriesIDOK
const PutEntriesIDOKCode int = 200

/*
PutEntriesIDOK OK

swagger:response putEntriesIdOK
*/
type PutEntriesIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Entry `json:"body,omitempty"`
}

// NewPutEntriesIDOK creates PutEntriesIDOK with default headers values
func NewPutEntriesIDOK() *PutEntriesIDOK {

	return &PutEntriesIDOK{}
}

// WithPayload adds the payload to the put entries Id o k response
func (o *PutEntriesIDOK) WithPayload(payload *models.Entry) *PutEntriesIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put entries Id o k response
func (o *PutEntriesIDOK) SetPayload(payload *models.Entry) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutEntriesIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
PutEntriesIDDefault Error

swagger:response putEntriesIdDefault
*/
type PutEntriesIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPutEntriesIDDefault creates PutEntriesIDDefault with default headers values
func NewPutEntriesIDDefault(code int) *PutEntriesIDDefault {
	if code <= 0 {
		code = 500
	}

	return &PutEntriesIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the put entries ID default response
func (o *PutEntriesIDDefault) WithStatusCode(code int) *PutEntriesIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the put entries ID default response
func (o *PutEntriesIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the put entries ID default response
func (o *PutEntriesIDDefault) WithPayload(payload *models.Error) *PutEntriesIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put entries ID default response
func (o *PutEntriesIDDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutEntriesIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
