// Code generated by go-swagger; DO NOT EDIT.

package category

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"hta_backend_2/models"
)

// DeleteSingleChoiceGroupIDNoContentCode is the HTTP code returned for type DeleteSingleChoiceGroupIDNoContent
const DeleteSingleChoiceGroupIDNoContentCode int = 204

/*
DeleteSingleChoiceGroupIDNoContent Deleted

swagger:response deleteSingleChoiceGroupIdNoContent
*/
type DeleteSingleChoiceGroupIDNoContent struct {
}

// NewDeleteSingleChoiceGroupIDNoContent creates DeleteSingleChoiceGroupIDNoContent with default headers values
func NewDeleteSingleChoiceGroupIDNoContent() *DeleteSingleChoiceGroupIDNoContent {

	return &DeleteSingleChoiceGroupIDNoContent{}
}

// WriteResponse to the client
func (o *DeleteSingleChoiceGroupIDNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

/*
DeleteSingleChoiceGroupIDDefault Error

swagger:response deleteSingleChoiceGroupIdDefault
*/
type DeleteSingleChoiceGroupIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteSingleChoiceGroupIDDefault creates DeleteSingleChoiceGroupIDDefault with default headers values
func NewDeleteSingleChoiceGroupIDDefault(code int) *DeleteSingleChoiceGroupIDDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteSingleChoiceGroupIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete single choice group ID default response
func (o *DeleteSingleChoiceGroupIDDefault) WithStatusCode(code int) *DeleteSingleChoiceGroupIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete single choice group ID default response
func (o *DeleteSingleChoiceGroupIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete single choice group ID default response
func (o *DeleteSingleChoiceGroupIDDefault) WithPayload(payload *models.Error) *DeleteSingleChoiceGroupIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete single choice group ID default response
func (o *DeleteSingleChoiceGroupIDDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteSingleChoiceGroupIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
