// Code generated by go-swagger; DO NOT EDIT.

package category

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/pl33/hta-backend/schemas"
)

// DeleteSingleChoiceIDHandlerFunc turns a function with the right signature into a delete single choice ID handler
type DeleteSingleChoiceIDHandlerFunc func(DeleteSingleChoiceIDParams, *schemas.User) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteSingleChoiceIDHandlerFunc) Handle(params DeleteSingleChoiceIDParams, principal *schemas.User) middleware.Responder {
	return fn(params, principal)
}

// DeleteSingleChoiceIDHandler interface for that can handle valid delete single choice ID params
type DeleteSingleChoiceIDHandler interface {
	Handle(DeleteSingleChoiceIDParams, *schemas.User) middleware.Responder
}

// NewDeleteSingleChoiceID creates a new http.Handler for the delete single choice ID operation
func NewDeleteSingleChoiceID(ctx *middleware.Context, handler DeleteSingleChoiceIDHandler) *DeleteSingleChoiceID {
	return &DeleteSingleChoiceID{Context: ctx, Handler: handler}
}

/*
	DeleteSingleChoiceID swagger:route DELETE /single_choice/{id} category deleteSingleChoiceId

DeleteSingleChoiceID delete single choice ID API
*/
type DeleteSingleChoiceID struct {
	Context *middleware.Context
	Handler DeleteSingleChoiceIDHandler
}

func (o *DeleteSingleChoiceID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteSingleChoiceIDParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *schemas.User
	if uprinc != nil {
		principal = uprinc.(*schemas.User) // this is really a schemas.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
