// Code generated by go-swagger; DO NOT EDIT.

package category

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/pl33/hta-backend/models"
)

// DeleteMultiChoiceIDNoContentCode is the HTTP code returned for type DeleteMultiChoiceIDNoContent
const DeleteMultiChoiceIDNoContentCode int = 204

/*
DeleteMultiChoiceIDNoContent Deleted

swagger:response deleteMultiChoiceIdNoContent
*/
type DeleteMultiChoiceIDNoContent struct {
}

// NewDeleteMultiChoiceIDNoContent creates DeleteMultiChoiceIDNoContent with default headers values
func NewDeleteMultiChoiceIDNoContent() *DeleteMultiChoiceIDNoContent {

	return &DeleteMultiChoiceIDNoContent{}
}

// WriteResponse to the client
func (o *DeleteMultiChoiceIDNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

/*
DeleteMultiChoiceIDDefault Error

swagger:response deleteMultiChoiceIdDefault
*/
type DeleteMultiChoiceIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteMultiChoiceIDDefault creates DeleteMultiChoiceIDDefault with default headers values
func NewDeleteMultiChoiceIDDefault(code int) *DeleteMultiChoiceIDDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteMultiChoiceIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete multi choice ID default response
func (o *DeleteMultiChoiceIDDefault) WithStatusCode(code int) *DeleteMultiChoiceIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete multi choice ID default response
func (o *DeleteMultiChoiceIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete multi choice ID default response
func (o *DeleteMultiChoiceIDDefault) WithPayload(payload *models.Error) *DeleteMultiChoiceIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete multi choice ID default response
func (o *DeleteMultiChoiceIDDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteMultiChoiceIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
