// Code generated by go-swagger; DO NOT EDIT.

package category

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"hta_backend_2/models"
)

// GetSingleChoiceGroupGroupIDSingleChoiceHandlerFunc turns a function with the right signature into a get single choice group group ID single choice handler
type GetSingleChoiceGroupGroupIDSingleChoiceHandlerFunc func(GetSingleChoiceGroupGroupIDSingleChoiceParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn GetSingleChoiceGroupGroupIDSingleChoiceHandlerFunc) Handle(params GetSingleChoiceGroupGroupIDSingleChoiceParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// GetSingleChoiceGroupGroupIDSingleChoiceHandler interface for that can handle valid get single choice group group ID single choice params
type GetSingleChoiceGroupGroupIDSingleChoiceHandler interface {
	Handle(GetSingleChoiceGroupGroupIDSingleChoiceParams, *models.User) middleware.Responder
}

// NewGetSingleChoiceGroupGroupIDSingleChoice creates a new http.Handler for the get single choice group group ID single choice operation
func NewGetSingleChoiceGroupGroupIDSingleChoice(ctx *middleware.Context, handler GetSingleChoiceGroupGroupIDSingleChoiceHandler) *GetSingleChoiceGroupGroupIDSingleChoice {
	return &GetSingleChoiceGroupGroupIDSingleChoice{Context: ctx, Handler: handler}
}

/*
	GetSingleChoiceGroupGroupIDSingleChoice swagger:route GET /single_choice_group/{group_id}/single_choice/ category getSingleChoiceGroupGroupIdSingleChoice

GetSingleChoiceGroupGroupIDSingleChoice get single choice group group ID single choice API
*/
type GetSingleChoiceGroupGroupIDSingleChoice struct {
	Context *middleware.Context
	Handler GetSingleChoiceGroupGroupIDSingleChoiceHandler
}

func (o *GetSingleChoiceGroupGroupIDSingleChoice) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetSingleChoiceGroupGroupIDSingleChoiceParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
