// Code generated by go-swagger; DO NOT EDIT.

package category

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/pl33/hta-backend/schemas"
)

// GetCategoryCategoryIDSingleChoiceGroupHandlerFunc turns a function with the right signature into a get category category ID single choice group handler
type GetCategoryCategoryIDSingleChoiceGroupHandlerFunc func(GetCategoryCategoryIDSingleChoiceGroupParams, *schemas.User) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCategoryCategoryIDSingleChoiceGroupHandlerFunc) Handle(params GetCategoryCategoryIDSingleChoiceGroupParams, principal *schemas.User) middleware.Responder {
	return fn(params, principal)
}

// GetCategoryCategoryIDSingleChoiceGroupHandler interface for that can handle valid get category category ID single choice group params
type GetCategoryCategoryIDSingleChoiceGroupHandler interface {
	Handle(GetCategoryCategoryIDSingleChoiceGroupParams, *schemas.User) middleware.Responder
}

// NewGetCategoryCategoryIDSingleChoiceGroup creates a new http.Handler for the get category category ID single choice group operation
func NewGetCategoryCategoryIDSingleChoiceGroup(ctx *middleware.Context, handler GetCategoryCategoryIDSingleChoiceGroupHandler) *GetCategoryCategoryIDSingleChoiceGroup {
	return &GetCategoryCategoryIDSingleChoiceGroup{Context: ctx, Handler: handler}
}

/*
	GetCategoryCategoryIDSingleChoiceGroup swagger:route GET /category/{category_id}/single_choice_group/ category getCategoryCategoryIdSingleChoiceGroup

GetCategoryCategoryIDSingleChoiceGroup get category category ID single choice group API
*/
type GetCategoryCategoryIDSingleChoiceGroup struct {
	Context *middleware.Context
	Handler GetCategoryCategoryIDSingleChoiceGroupHandler
}

func (o *GetCategoryCategoryIDSingleChoiceGroup) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetCategoryCategoryIDSingleChoiceGroupParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *schemas.User
	if uprinc != nil {
		principal = uprinc.(*schemas.User) // this is really a schemas.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
