// Code generated by go-swagger; DO NOT EDIT.

package category

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"

	"github.com/go-openapi/swag"
)

// GetSingleChoiceGroupGroupIDSingleChoiceURL generates an URL for the get single choice group group ID single choice operation
type GetSingleChoiceGroupGroupIDSingleChoiceURL struct {
	GroupID int64

	First *int32
	Limit *int32

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetSingleChoiceGroupGroupIDSingleChoiceURL) WithBasePath(bp string) *GetSingleChoiceGroupGroupIDSingleChoiceURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetSingleChoiceGroupGroupIDSingleChoiceURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *GetSingleChoiceGroupGroupIDSingleChoiceURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/single_choice_group/{group_id}/single_choice/"

	groupID := swag.FormatInt64(o.GroupID)
	if groupID != "" {
		_path = strings.Replace(_path, "{group_id}", groupID, -1)
	} else {
		return nil, errors.New("groupId is required on GetSingleChoiceGroupGroupIDSingleChoiceURL")
	}

	_basePath := o._basePath
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var firstQ string
	if o.First != nil {
		firstQ = swag.FormatInt32(*o.First)
	}
	if firstQ != "" {
		qs.Set("first", firstQ)
	}

	var limitQ string
	if o.Limit != nil {
		limitQ = swag.FormatInt32(*o.Limit)
	}
	if limitQ != "" {
		qs.Set("limit", limitQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *GetSingleChoiceGroupGroupIDSingleChoiceURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *GetSingleChoiceGroupGroupIDSingleChoiceURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *GetSingleChoiceGroupGroupIDSingleChoiceURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on GetSingleChoiceGroupGroupIDSingleChoiceURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on GetSingleChoiceGroupGroupIDSingleChoiceURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *GetSingleChoiceGroupGroupIDSingleChoiceURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
