// Code generated by go-swagger; DO NOT EDIT.

package category

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/pl33/hta-backend/schemas"
)

// GetCategoryIDHandlerFunc turns a function with the right signature into a get category ID handler
type GetCategoryIDHandlerFunc func(GetCategoryIDParams, *schemas.User) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCategoryIDHandlerFunc) Handle(params GetCategoryIDParams, principal *schemas.User) middleware.Responder {
	return fn(params, principal)
}

// GetCategoryIDHandler interface for that can handle valid get category ID params
type GetCategoryIDHandler interface {
	Handle(GetCategoryIDParams, *schemas.User) middleware.Responder
}

// NewGetCategoryID creates a new http.Handler for the get category ID operation
func NewGetCategoryID(ctx *middleware.Context, handler GetCategoryIDHandler) *GetCategoryID {
	return &GetCategoryID{Context: ctx, Handler: handler}
}

/*
	GetCategoryID swagger:route GET /category/{id} category getCategoryId

GetCategoryID get category ID API
*/
type GetCategoryID struct {
	Context *middleware.Context
	Handler GetCategoryIDHandler
}

func (o *GetCategoryID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetCategoryIDParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *schemas.User
	if uprinc != nil {
		principal = uprinc.(*schemas.User) // this is really a schemas.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
