// Code generated by go-swagger; DO NOT EDIT.

package category

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"hta_backend_2/models"
)

// GetCategoryOKCode is the HTTP code returned for type GetCategoryOK
const GetCategoryOKCode int = 200

/*
GetCategoryOK List of categories

swagger:response getCategoryOK
*/
type GetCategoryOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Category `json:"body,omitempty"`
}

// NewGetCategoryOK creates GetCategoryOK with default headers values
func NewGetCategoryOK() *GetCategoryOK {

	return &GetCategoryOK{}
}

// WithPayload adds the payload to the get category o k response
func (o *GetCategoryOK) WithPayload(payload []*models.Category) *GetCategoryOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get category o k response
func (o *GetCategoryOK) SetPayload(payload []*models.Category) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCategoryOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Category, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*
GetCategoryDefault Error

swagger:response getCategoryDefault
*/
type GetCategoryDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetCategoryDefault creates GetCategoryDefault with default headers values
func NewGetCategoryDefault(code int) *GetCategoryDefault {
	if code <= 0 {
		code = 500
	}

	return &GetCategoryDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get category default response
func (o *GetCategoryDefault) WithStatusCode(code int) *GetCategoryDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get category default response
func (o *GetCategoryDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get category default response
func (o *GetCategoryDefault) WithPayload(payload *models.Error) *GetCategoryDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get category default response
func (o *GetCategoryDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCategoryDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
