// Code generated by go-swagger; DO NOT EDIT.

package category

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetSingleChoiceGroupGroupIDSingleChoiceParams creates a new GetSingleChoiceGroupGroupIDSingleChoiceParams object
// with the default values initialized.
func NewGetSingleChoiceGroupGroupIDSingleChoiceParams() GetSingleChoiceGroupGroupIDSingleChoiceParams {

	var (
		// initialize parameters with default values

		firstDefault = int32(0)
	)

	return GetSingleChoiceGroupGroupIDSingleChoiceParams{
		First: &firstDefault,
	}
}

// GetSingleChoiceGroupGroupIDSingleChoiceParams contains all the bound params for the get single choice group group ID single choice operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetSingleChoiceGroupGroupIDSingleChoice
type GetSingleChoiceGroupGroupIDSingleChoiceParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  In: query
	  Default: 0
	*/
	First *int32
	/*
	  Required: true
	  In: path
	*/
	GroupID int64
	/*
	  In: query
	*/
	Limit *int32
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetSingleChoiceGroupGroupIDSingleChoiceParams() beforehand.
func (o *GetSingleChoiceGroupGroupIDSingleChoiceParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qFirst, qhkFirst, _ := qs.GetOK("first")
	if err := o.bindFirst(qFirst, qhkFirst, route.Formats); err != nil {
		res = append(res, err)
	}

	rGroupID, rhkGroupID, _ := route.Params.GetOK("group_id")
	if err := o.bindGroupID(rGroupID, rhkGroupID, route.Formats); err != nil {
		res = append(res, err)
	}

	qLimit, qhkLimit, _ := qs.GetOK("limit")
	if err := o.bindLimit(qLimit, qhkLimit, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindFirst binds and validates parameter First from query.
func (o *GetSingleChoiceGroupGroupIDSingleChoiceParams) bindFirst(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewGetSingleChoiceGroupGroupIDSingleChoiceParams()
		return nil
	}

	value, err := swag.ConvertInt32(raw)
	if err != nil {
		return errors.InvalidType("first", "query", "int32", raw)
	}
	o.First = &value

	return nil
}

// bindGroupID binds and validates parameter GroupID from path.
func (o *GetSingleChoiceGroupGroupIDSingleChoiceParams) bindGroupID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("group_id", "path", "int64", raw)
	}
	o.GroupID = value

	return nil
}

// bindLimit binds and validates parameter Limit from query.
func (o *GetSingleChoiceGroupGroupIDSingleChoiceParams) bindLimit(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertInt32(raw)
	if err != nil {
		return errors.InvalidType("limit", "query", "int32", raw)
	}
	o.Limit = &value

	return nil
}
