// Code generated by go-swagger; DO NOT EDIT.

package category

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"hta_backend_2/models"
)

// GetCategoryCategoryIDMultiChoiceHandlerFunc turns a function with the right signature into a get category category ID multi choice handler
type GetCategoryCategoryIDMultiChoiceHandlerFunc func(GetCategoryCategoryIDMultiChoiceParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCategoryCategoryIDMultiChoiceHandlerFunc) Handle(params GetCategoryCategoryIDMultiChoiceParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// GetCategoryCategoryIDMultiChoiceHandler interface for that can handle valid get category category ID multi choice params
type GetCategoryCategoryIDMultiChoiceHandler interface {
	Handle(GetCategoryCategoryIDMultiChoiceParams, *models.User) middleware.Responder
}

// NewGetCategoryCategoryIDMultiChoice creates a new http.Handler for the get category category ID multi choice operation
func NewGetCategoryCategoryIDMultiChoice(ctx *middleware.Context, handler GetCategoryCategoryIDMultiChoiceHandler) *GetCategoryCategoryIDMultiChoice {
	return &GetCategoryCategoryIDMultiChoice{Context: ctx, Handler: handler}
}

/*
	GetCategoryCategoryIDMultiChoice swagger:route GET /category/{category_id}/multi_choice/ category getCategoryCategoryIdMultiChoice

GetCategoryCategoryIDMultiChoice get category category ID multi choice API
*/
type GetCategoryCategoryIDMultiChoice struct {
	Context *middleware.Context
	Handler GetCategoryCategoryIDMultiChoiceHandler
}

func (o *GetCategoryCategoryIDMultiChoice) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetCategoryCategoryIDMultiChoiceParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
