// Code generated by go-swagger; DO NOT EDIT.

package category

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/pl33/hta-backend/schemas"
)

// GetMultiChoiceIDHandlerFunc turns a function with the right signature into a get multi choice ID handler
type GetMultiChoiceIDHandlerFunc func(GetMultiChoiceIDParams, *schemas.User) middleware.Responder

// Handle executing the request and returning a response
func (fn GetMultiChoiceIDHandlerFunc) Handle(params GetMultiChoiceIDParams, principal *schemas.User) middleware.Responder {
	return fn(params, principal)
}

// GetMultiChoiceIDHandler interface for that can handle valid get multi choice ID params
type GetMultiChoiceIDHandler interface {
	Handle(GetMultiChoiceIDParams, *schemas.User) middleware.Responder
}

// NewGetMultiChoiceID creates a new http.Handler for the get multi choice ID operation
func NewGetMultiChoiceID(ctx *middleware.Context, handler GetMultiChoiceIDHandler) *GetMultiChoiceID {
	return &GetMultiChoiceID{Context: ctx, Handler: handler}
}

/*
	GetMultiChoiceID swagger:route GET /multi_choice/{id} category getMultiChoiceId

GetMultiChoiceID get multi choice ID API
*/
type GetMultiChoiceID struct {
	Context *middleware.Context
	Handler GetMultiChoiceIDHandler
}

func (o *GetMultiChoiceID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetMultiChoiceIDParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *schemas.User
	if uprinc != nil {
		principal = uprinc.(*schemas.User) // this is really a schemas.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
