// Code generated by go-swagger; DO NOT EDIT.

package category

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"hta_backend_2/models"
)

// PostCategoryHandlerFunc turns a function with the right signature into a post category handler
type PostCategoryHandlerFunc func(PostCategoryParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn PostCategoryHandlerFunc) Handle(params PostCategoryParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// PostCategoryHandler interface for that can handle valid post category params
type PostCategoryHandler interface {
	Handle(PostCategoryParams, *models.User) middleware.Responder
}

// NewPostCategory creates a new http.Handler for the post category operation
func NewPostCategory(ctx *middleware.Context, handler PostCategoryHandler) *PostCategory {
	return &PostCategory{Context: ctx, Handler: handler}
}

/*
	PostCategory swagger:route POST /category/ category postCategory

PostCategory post category API
*/
type PostCategory struct {
	Context *middleware.Context
	Handler PostCategoryHandler
}

func (o *PostCategory) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostCategoryParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
