// Code generated by go-swagger; DO NOT EDIT.

package category

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"hta_backend_2/models"
)

// PostSingleChoiceGroupGroupIDSingleChoiceHandlerFunc turns a function with the right signature into a post single choice group group ID single choice handler
type PostSingleChoiceGroupGroupIDSingleChoiceHandlerFunc func(PostSingleChoiceGroupGroupIDSingleChoiceParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn PostSingleChoiceGroupGroupIDSingleChoiceHandlerFunc) Handle(params PostSingleChoiceGroupGroupIDSingleChoiceParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// PostSingleChoiceGroupGroupIDSingleChoiceHandler interface for that can handle valid post single choice group group ID single choice params
type PostSingleChoiceGroupGroupIDSingleChoiceHandler interface {
	Handle(PostSingleChoiceGroupGroupIDSingleChoiceParams, *models.User) middleware.Responder
}

// NewPostSingleChoiceGroupGroupIDSingleChoice creates a new http.Handler for the post single choice group group ID single choice operation
func NewPostSingleChoiceGroupGroupIDSingleChoice(ctx *middleware.Context, handler PostSingleChoiceGroupGroupIDSingleChoiceHandler) *PostSingleChoiceGroupGroupIDSingleChoice {
	return &PostSingleChoiceGroupGroupIDSingleChoice{Context: ctx, Handler: handler}
}

/*
	PostSingleChoiceGroupGroupIDSingleChoice swagger:route POST /single_choice_group/{group_id}/single_choice/ category postSingleChoiceGroupGroupIdSingleChoice

PostSingleChoiceGroupGroupIDSingleChoice post single choice group group ID single choice API
*/
type PostSingleChoiceGroupGroupIDSingleChoice struct {
	Context *middleware.Context
	Handler PostSingleChoiceGroupGroupIDSingleChoiceHandler
}

func (o *PostSingleChoiceGroupGroupIDSingleChoice) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostSingleChoiceGroupGroupIDSingleChoiceParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
