// Code generated by go-swagger; DO NOT EDIT.

package category

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"hta_backend_2/models"
)

// PostCategoryCreatedCode is the HTTP code returned for type PostCategoryCreated
const PostCategoryCreatedCode int = 201

/*
PostCategoryCreated Created

swagger:response postCategoryCreated
*/
type PostCategoryCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Category `json:"body,omitempty"`
}

// NewPostCategoryCreated creates PostCategoryCreated with default headers values
func NewPostCategoryCreated() *PostCategoryCreated {

	return &PostCategoryCreated{}
}

// WithPayload adds the payload to the post category created response
func (o *PostCategoryCreated) WithPayload(payload *models.Category) *PostCategoryCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post category created response
func (o *PostCategoryCreated) SetPayload(payload *models.Category) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostCategoryCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
PostCategoryDefault Error

swagger:response postCategoryDefault
*/
type PostCategoryDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostCategoryDefault creates PostCategoryDefault with default headers values
func NewPostCategoryDefault(code int) *PostCategoryDefault {
	if code <= 0 {
		code = 500
	}

	return &PostCategoryDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the post category default response
func (o *PostCategoryDefault) WithStatusCode(code int) *PostCategoryDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the post category default response
func (o *PostCategoryDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the post category default response
func (o *PostCategoryDefault) WithPayload(payload *models.Error) *PostCategoryDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post category default response
func (o *PostCategoryDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostCategoryDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
