// Code generated by go-swagger; DO NOT EDIT.

package category

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/pl33/hta-backend/models"
)

// NewPostCategoryCategoryIDSingleChoiceGroupParams creates a new PostCategoryCategoryIDSingleChoiceGroupParams object
//
// There are no default values defined in the spec.
func NewPostCategoryCategoryIDSingleChoiceGroupParams() PostCategoryCategoryIDSingleChoiceGroupParams {

	return PostCategoryCategoryIDSingleChoiceGroupParams{}
}

// PostCategoryCategoryIDSingleChoiceGroupParams contains all the bound params for the post category category ID single choice group operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostCategoryCategoryIDSingleChoiceGroup
type PostCategoryCategoryIDSingleChoiceGroupParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  In: body
	*/
	Body *models.CategorySingleChoiceGroup
	/*
	  Required: true
	  In: path
	*/
	CategoryID int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostCategoryCategoryIDSingleChoiceGroupParams() beforehand.
func (o *PostCategoryCategoryIDSingleChoiceGroupParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.CategorySingleChoiceGroup
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("body", "body", "", err))
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(r.Context())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Body = &body
			}
		}
	}

	rCategoryID, rhkCategoryID, _ := route.Params.GetOK("category_id")
	if err := o.bindCategoryID(rCategoryID, rhkCategoryID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindCategoryID binds and validates parameter CategoryID from path.
func (o *PostCategoryCategoryIDSingleChoiceGroupParams) bindCategoryID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("category_id", "path", "int64", raw)
	}
	o.CategoryID = value

	return nil
}
