// Code generated by go-swagger; DO NOT EDIT.

package category

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"hta_backend_2/models"
)

// PostCategoryCategoryIDMultiChoiceCreatedCode is the HTTP code returned for type PostCategoryCategoryIDMultiChoiceCreated
const PostCategoryCategoryIDMultiChoiceCreatedCode int = 201

/*
PostCategoryCategoryIDMultiChoiceCreated Created

swagger:response postCategoryCategoryIdMultiChoiceCreated
*/
type PostCategoryCategoryIDMultiChoiceCreated struct {

	/*
	  In: Body
	*/
	Payload *models.CategoryMultiChoice `json:"body,omitempty"`
}

// NewPostCategoryCategoryIDMultiChoiceCreated creates PostCategoryCategoryIDMultiChoiceCreated with default headers values
func NewPostCategoryCategoryIDMultiChoiceCreated() *PostCategoryCategoryIDMultiChoiceCreated {

	return &PostCategoryCategoryIDMultiChoiceCreated{}
}

// WithPayload adds the payload to the post category category Id multi choice created response
func (o *PostCategoryCategoryIDMultiChoiceCreated) WithPayload(payload *models.CategoryMultiChoice) *PostCategoryCategoryIDMultiChoiceCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post category category Id multi choice created response
func (o *PostCategoryCategoryIDMultiChoiceCreated) SetPayload(payload *models.CategoryMultiChoice) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostCategoryCategoryIDMultiChoiceCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
PostCategoryCategoryIDMultiChoiceDefault Error

swagger:response postCategoryCategoryIdMultiChoiceDefault
*/
type PostCategoryCategoryIDMultiChoiceDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostCategoryCategoryIDMultiChoiceDefault creates PostCategoryCategoryIDMultiChoiceDefault with default headers values
func NewPostCategoryCategoryIDMultiChoiceDefault(code int) *PostCategoryCategoryIDMultiChoiceDefault {
	if code <= 0 {
		code = 500
	}

	return &PostCategoryCategoryIDMultiChoiceDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the post category category ID multi choice default response
func (o *PostCategoryCategoryIDMultiChoiceDefault) WithStatusCode(code int) *PostCategoryCategoryIDMultiChoiceDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the post category category ID multi choice default response
func (o *PostCategoryCategoryIDMultiChoiceDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the post category category ID multi choice default response
func (o *PostCategoryCategoryIDMultiChoiceDefault) WithPayload(payload *models.Error) *PostCategoryCategoryIDMultiChoiceDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post category category ID multi choice default response
func (o *PostCategoryCategoryIDMultiChoiceDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostCategoryCategoryIDMultiChoiceDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
