// Code generated by go-swagger; DO NOT EDIT.

package category

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"hta_backend_2/models"
)

// PostCategoryCategoryIDMultiChoiceHandlerFunc turns a function with the right signature into a post category category ID multi choice handler
type PostCategoryCategoryIDMultiChoiceHandlerFunc func(PostCategoryCategoryIDMultiChoiceParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn PostCategoryCategoryIDMultiChoiceHandlerFunc) Handle(params PostCategoryCategoryIDMultiChoiceParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// PostCategoryCategoryIDMultiChoiceHandler interface for that can handle valid post category category ID multi choice params
type PostCategoryCategoryIDMultiChoiceHandler interface {
	Handle(PostCategoryCategoryIDMultiChoiceParams, *models.User) middleware.Responder
}

// NewPostCategoryCategoryIDMultiChoice creates a new http.Handler for the post category category ID multi choice operation
func NewPostCategoryCategoryIDMultiChoice(ctx *middleware.Context, handler PostCategoryCategoryIDMultiChoiceHandler) *PostCategoryCategoryIDMultiChoice {
	return &PostCategoryCategoryIDMultiChoice{Context: ctx, Handler: handler}
}

/*
	PostCategoryCategoryIDMultiChoice swagger:route POST /category/{category_id}/multi_choice/ category postCategoryCategoryIdMultiChoice

PostCategoryCategoryIDMultiChoice post category category ID multi choice API
*/
type PostCategoryCategoryIDMultiChoice struct {
	Context *middleware.Context
	Handler PostCategoryCategoryIDMultiChoiceHandler
}

func (o *PostCategoryCategoryIDMultiChoice) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostCategoryCategoryIDMultiChoiceParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
