// Code generated by go-swagger; DO NOT EDIT.

package category

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"

	"github.com/go-openapi/swag"
)

// PostCategoryCategoryIDSingleChoiceGroupURL generates an URL for the post category category ID single choice group operation
type PostCategoryCategoryIDSingleChoiceGroupURL struct {
	CategoryID int64

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *PostCategoryCategoryIDSingleChoiceGroupURL) WithBasePath(bp string) *PostCategoryCategoryIDSingleChoiceGroupURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *PostCategoryCategoryIDSingleChoiceGroupURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *PostCategoryCategoryIDSingleChoiceGroupURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/category/{category_id}/single_choice_group/"

	categoryID := swag.FormatInt64(o.CategoryID)
	if categoryID != "" {
		_path = strings.Replace(_path, "{category_id}", categoryID, -1)
	} else {
		return nil, errors.New("categoryId is required on PostCategoryCategoryIDSingleChoiceGroupURL")
	}

	_basePath := o._basePath
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *PostCategoryCategoryIDSingleChoiceGroupURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *PostCategoryCategoryIDSingleChoiceGroupURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *PostCategoryCategoryIDSingleChoiceGroupURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on PostCategoryCategoryIDSingleChoiceGroupURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on PostCategoryCategoryIDSingleChoiceGroupURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *PostCategoryCategoryIDSingleChoiceGroupURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
