// Code generated by go-swagger; DO NOT EDIT.

package category

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/pl33/hta-backend/schemas"
)

// PutSingleChoiceGroupIDHandlerFunc turns a function with the right signature into a put single choice group ID handler
type PutSingleChoiceGroupIDHandlerFunc func(PutSingleChoiceGroupIDParams, *schemas.User) middleware.Responder

// Handle executing the request and returning a response
func (fn PutSingleChoiceGroupIDHandlerFunc) Handle(params PutSingleChoiceGroupIDParams, principal *schemas.User) middleware.Responder {
	return fn(params, principal)
}

// PutSingleChoiceGroupIDHandler interface for that can handle valid put single choice group ID params
type PutSingleChoiceGroupIDHandler interface {
	Handle(PutSingleChoiceGroupIDParams, *schemas.User) middleware.Responder
}

// NewPutSingleChoiceGroupID creates a new http.Handler for the put single choice group ID operation
func NewPutSingleChoiceGroupID(ctx *middleware.Context, handler PutSingleChoiceGroupIDHandler) *PutSingleChoiceGroupID {
	return &PutSingleChoiceGroupID{Context: ctx, Handler: handler}
}

/*
	PutSingleChoiceGroupID swagger:route PUT /single_choice_group/{id} category putSingleChoiceGroupId

PutSingleChoiceGroupID put single choice group ID API
*/
type PutSingleChoiceGroupID struct {
	Context *middleware.Context
	Handler PutSingleChoiceGroupIDHandler
}

func (o *PutSingleChoiceGroupID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPutSingleChoiceGroupIDParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *schemas.User
	if uprinc != nil {
		principal = uprinc.(*schemas.User) // this is really a schemas.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
