// Code generated by go-swagger; DO NOT EDIT.

package category

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"hta_backend_2/models"
)

// PutCategoryIDHandlerFunc turns a function with the right signature into a put category ID handler
type PutCategoryIDHandlerFunc func(PutCategoryIDParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn PutCategoryIDHandlerFunc) Handle(params PutCategoryIDParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// PutCategoryIDHandler interface for that can handle valid put category ID params
type PutCategoryIDHandler interface {
	Handle(PutCategoryIDParams, *models.User) middleware.Responder
}

// NewPutCategoryID creates a new http.Handler for the put category ID operation
func NewPutCategoryID(ctx *middleware.Context, handler PutCategoryIDHandler) *PutCategoryID {
	return &PutCategoryID{Context: ctx, Handler: handler}
}

/*
	PutCategoryID swagger:route PUT /category/{id} category putCategoryId

PutCategoryID put category ID API
*/
type PutCategoryID struct {
	Context *middleware.Context
	Handler PutCategoryIDHandler
}

func (o *PutCategoryID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPutCategoryIDParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
