// Code generated by go-swagger; DO NOT EDIT.

package category

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/pl33/hta-backend/schemas"
)

// PutSingleChoiceIDHandlerFunc turns a function with the right signature into a put single choice ID handler
type PutSingleChoiceIDHandlerFunc func(PutSingleChoiceIDParams, *schemas.User) middleware.Responder

// Handle executing the request and returning a response
func (fn PutSingleChoiceIDHandlerFunc) Handle(params PutSingleChoiceIDParams, principal *schemas.User) middleware.Responder {
	return fn(params, principal)
}

// PutSingleChoiceIDHandler interface for that can handle valid put single choice ID params
type PutSingleChoiceIDHandler interface {
	Handle(PutSingleChoiceIDParams, *schemas.User) middleware.Responder
}

// NewPutSingleChoiceID creates a new http.Handler for the put single choice ID operation
func NewPutSingleChoiceID(ctx *middleware.Context, handler PutSingleChoiceIDHandler) *PutSingleChoiceID {
	return &PutSingleChoiceID{Context: ctx, Handler: handler}
}

/*
	PutSingleChoiceID swagger:route PUT /single_choice/{id} category putSingleChoiceId

PutSingleChoiceID put single choice ID API
*/
type PutSingleChoiceID struct {
	Context *middleware.Context
	Handler PutSingleChoiceIDHandler
}

func (o *PutSingleChoiceID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPutSingleChoiceIDParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *schemas.User
	if uprinc != nil {
		principal = uprinc.(*schemas.User) // this is really a schemas.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
