// Code generated by go-swagger; DO NOT EDIT.

package category

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"hta_backend_2/models"
)

// PutMultiChoiceIDHandlerFunc turns a function with the right signature into a put multi choice ID handler
type PutMultiChoiceIDHandlerFunc func(PutMultiChoiceIDParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn PutMultiChoiceIDHandlerFunc) Handle(params PutMultiChoiceIDParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// PutMultiChoiceIDHandler interface for that can handle valid put multi choice ID params
type PutMultiChoiceIDHandler interface {
	Handle(PutMultiChoiceIDParams, *models.User) middleware.Responder
}

// NewPutMultiChoiceID creates a new http.Handler for the put multi choice ID operation
func NewPutMultiChoiceID(ctx *middleware.Context, handler PutMultiChoiceIDHandler) *PutMultiChoiceID {
	return &PutMultiChoiceID{Context: ctx, Handler: handler}
}

/*
	PutMultiChoiceID swagger:route PUT /multi_choice/{id} category putMultiChoiceId

PutMultiChoiceID put multi choice ID API
*/
type PutMultiChoiceID struct {
	Context *middleware.Context
	Handler PutMultiChoiceIDHandler
}

func (o *PutMultiChoiceID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPutMultiChoiceIDParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
