// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// OidcInfo oidc info
//
// swagger:model oidc_info
type OidcInfo struct {

	// client id
	ClientID string `json:"client_id,omitempty"`

	// client secret
	ClientSecret string `json:"client_secret,omitempty"`

	// discovery url
	// Required: true
	DiscoveryURL *string `json:"discovery_url"`
}

// Validate validates this oidc info
func (m *OidcInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDiscoveryURL(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OidcInfo) validateDiscoveryURL(formats strfmt.Registry) error {

	if err := validate.Required("discovery_url", "body", m.DiscoveryURL); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this oidc info based on context it is used
func (m *OidcInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OidcInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OidcInfo) UnmarshalBinary(b []byte) error {
	var res OidcInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
